// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RotaViagem.Infra;

#nullable disable

namespace RotaViagem.Infra.Migrations
{
    [DbContext(typeof(RotaDbContext))]
    partial class RotaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RotaViagem.Domain.Rota", b =>
                {
                    b.Property<string>("Origem")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Destino")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal>("Custo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Origem", "Destino");

                    b.ToTable("Rotas");
                });
#pragma warning restore 612, 618
        }
    }
}
